# Azure App Service Deployment Workflow
name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: bihar-teacher-portal    # Set this to your app name
  AZURE_WEBAPP_PACKAGE_PATH: '.'             # Set this to the path to your web app project
  DOTNET_VERSION: '8.0.x'                    # Set this to the .NET version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Angular CLI
      run: npm install -g @angular/cli
    
    - name: Install Frontend dependencies
      run: npm install
      working-directory: ./Frontend
    
    - name: Build Frontend
      run: npm run build
      working-directory: ./Frontend
    
    - name: Copy Frontend to Backend wwwroot
      run: |
        mkdir -p Backend/WebAPI/wwwroot
        cp -r Frontend/dist/Frontend/* Backend/WebAPI/wwwroot/
    
    - name: Restore Backend dependencies
      run: dotnet restore
      working-directory: ./Backend
    
    - name: Build Backend
      run: dotnet build --configuration Release --no-restore
      working-directory: ./Backend
    
    - name: Publish Backend
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
      working-directory: ./Backend/WebAPI
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{env.DOTNET_ROOT}}/myapp